import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/**
 * Configures a Kotlin JVM project with plugins, repositories, tasks, and publishing settings.
 *
 * Applies the following plugins:
 * - Kotlin JVM plugin for compiling Kotlin source code targeting the JVM.
 * - Maven Publish plugin to enable publishing artifacts.
 * - Dokka plugin to generate documentation.
 * - SonarQube plugin for code quality analysis integration.
 *
 * Sets up the Maven Central repository as a central dependency resolution point.
 *
 * Configures SonarQube:
 * - Sets SonarQube project properties including project key, name, and authentication token.
 *
 * Defines custom build tasks:
 * - Creates a task to produce a JAR containing Javadoc generated by the Dokka plugin.
 * - Creates a task to produce a JAR containing all source code.
 *
 * Configures Kotlin compilation:
 * - Sets the target JVM version based on the defined library version.
 * - Adds strict compiler arguments for handling nullability.
 *
 * Configures unit testing:
 * - Sets the JUnit Platform as the test execution engine.
 *
 * Configures Maven publishing:
 * - Defines a Maven publication that includes the compiled code, Javadoc JAR, and source JAR.
 * - Dynamically selects the target Maven repository (releases or snapshots) based on the project version.
 * - Enables insecure protocol support for the Maven repository.
 * - Specifies hardcoded credentials for authenticating with the Maven repository.
 */
/**
 *
 */
/**
 * Configures a Kotlin JVM project with plugins, repositories, tasks, and publishing settings.
 *
 * Includes configuration for:
 * - Adding Kotlin JVM, Maven Publish, Dokka, and SonarQube plugins.
 * - Setting up Maven Central as the repository.
 * - Configuring SonarQube with project key, name, and token.
 * - Registering custom tasks for generating Javadoc and source JAR archives.
 * - Setting JVM target and compiler options for Kotlin compilation.
 * - Configuring unit testing to use the JUnit platform.
 * - Publishing built artifacts to Maven repositories with appropriate grouping, artifact, and version settings.
 *
 * The publishing configuration dynamically determines the target Maven repository (releases or snapshots)
 * based on the project's version. It also allows insecure HTTP connections for the repository
 * and uses hardcoded credentials for authentication.
 */
/**
 *
 */
// Ultra-einfache Version - garantiert funktionierend



plugins {
    alias(libs.plugins.kotlin.jvm)
    id("maven-publish")
    alias(libs.plugins.dokka)
    alias(libs.plugins.sonarqube)
}

repositories {
    mavenCentral()
}

sonar {
    properties {
        property("sonar.projectKey", "MMS-COMMON-UTIL")
        property("sonar.projectName", "MoMaSoft-Common-Util")
        property("sonar.token", "sqa_f08873c38b872bd5a87d0de33f7d7ac76f13b985")


    }
}

    tasks.register<Jar>("dokkaJavadocJar") {
        description = "Assembles Kotlin docs with Dokka"
        group = JavaBasePlugin.DOCUMENTATION_GROUP
        archiveClassifier.set("javadoc")
        from(tasks.dokkaJavadoc)
    }

    tasks.register<Jar>("sourcesJar") {
        description = "Assembles Kotlin sources with Dokka"
        group = JavaBasePlugin.DOCUMENTATION_GROUP
        archiveClassifier.set("sources")
        from(sourceSets["main"].allSource)
    }

    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        compilerOptions {
            jvmTarget.set(JvmTarget.fromTarget(libs.versions.jvmTarget.get()))
            freeCompilerArgs.set(listOf("-Xjsr305=strict"))
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }

    publishing {
        publications {
            create<MavenPublication>("mavenJava") {
                from(components["java"])
                artifact(tasks["dokkaJavadocJar"])
                artifact(tasks["sourcesJar"])
                groupId = group as String
                artifactId = project.name
                version = project.version.toString()
            }
        }
        repositories {
            maven {
                url = if (version.toString().endsWith("SNAPSHOT")) {
                    uri("https://192.168.2.33:9000/repository/maven-snapshots/")
                } else {
                    uri("https://192.168.2.33:9000/repository/maven-releases/")
                }
                isAllowInsecureProtocol = true
                credentials {
                    username = "admin"
                    password = "admin"
                }
            }
        }
    }
//}
