package de.modulix.mosimtech.model.urn

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import de.modulix.mosimtech.model.namespace.Namespace
import de.modulix.mosimtech.serializer.UrnDeserializer
import de.modulix.mosimtech.serializer.UrnSerializer

/**
 * Represents a Uniform Resource Name (URN) with a namespace, a namespace-specific string (NSS),
 * and an optional namespace identifier (NID).
 *
 * A URN (Uniform Resource Name) is an URI (Uniform Resource Identifier) that uniquely and permanently identifies a resource.
 * This class provides the structure and essential parts of an URN.
 *
 * @property namespace The namespace of the URN. This is a higher-level category or domain that helps
 *                     uniquely identify the resource. Example: "urn:isbn".
 * @property nss The namespace-specific string of the URN. This is the specific part of the URN that identifies
 *               a particular resource within the given namespace. Example: "978-3-16-148410-0" for a book in the ISBN namespace.
 * @property nid The optional namespace identifier of the URN. This could be used for additional identification purposes or specific
 *               implementation details. Example: An identifier for versions or special distinctions.
 *
 * Example of a complete URN without NID:
 * - Complete URN: "urn:isbn:978-3-16-148410-0"
 * - Namespace: "isbn"
 * - Namespace-specific string (NSS): "978-3-16-148410-0"
 * - Optional namespace identifier (NID): not present in this example
 *
 * Example of a complete URN with all components:
 * - Complete URN: "urn:user:keycloak:978-3-16-148410-0"
 * - Namespace: "user"
 * - Namespace-specific string (NSS): "978-3-16-148410-0"
 * - Optional namespace identifier (NID): keycloak
 *
 */
@JsonSerialize(using = UrnSerializer::class)
@JsonDeserialize(using = UrnDeserializer::class)
open class Urn() : UrnDefinition {

    @JsonProperty("namespace")
    override lateinit var namespace: String

    @JsonProperty("nss")
    override lateinit var nss: String

    @JsonProperty("nid")
    override var nid: Set<String>? = null

    constructor(namespace: String, nss: String, nid: Set<String>? = null) : this() {
        this.namespace = namespace
        this.nss = nss
        this.nid = nid
    }

    /**
     * Constructs an instance of the `Urn` class by assigning the provided `namespace`, `nss`,
     * and optionally `nid` values.
     *
     * @param namespace The `Namespace` object representing the namespace identifier.
     * @param nss The namespace-specific string (NSS) part of the URN.
     * @param nid A set of namespace identifiers (NID) which are optional.
     */
    constructor(namespace: Namespace, nss: String, nid: Set<String>? = null) : this(
        namespace = namespace.identifier,
        nss = nss,
        nid = nid
    )


    /**
     * Constructs an instance of the Urn class from the given URN string.
     *
     * This constructor uses the `parse` function to parse the provided `urnString` and
     * initialize an Urn object. If the `urnString` cannot be parsed, the initialization
     * may result in a null object, depending on the implementation of the `parse` function.
     *
     * @param urnString The string representation of a URN to be parsed and used to initialize the Urn object.
     */
    constructor(urnString: String) : this(parse(urnString)!!)

    /**
     * Private constructor for the Urn class that initializes the instance with
     * the namespace, namespace-specific string (NSS), and optional namespace identifier (NID)
     * from another Urn instance.
     *
     * @param data The Urn instance from which to copy the namespace, NSS, and NID values.
     */
    constructor(data: Urn) : this(data.namespace, data.nss, data.nid)


    /**
     * Converts the URN components to a string representation.
     *
     * @return A string in the format "urn:<namespace>:<nss>" if the NID is not specified;
     *         otherwise, the format will be "urn:<namespace>:<nss>:<nss>".
     */
    override fun toUrnString(): String {
        return if (nid == null) "urn:${namespace}:$nss"
        else {
            "urn:${namespace}:${nid!!.joinToString(":") { it }}:$nss"
        }
    }

    /**
     * Creates a string representation of the URN.
     *
     * @return A string representing the URN in the format defined by `toUrnString`.
     */
    override fun toString(): String {
        return toUrnString()
    }

    /**
     * Compares this `Urn` instance with another `Urn` instance for equality.
     *
     * The equality is determined by comparing the string representation of this URN,
     * generated by the `toUrnString` method, with the provided `Urn` instance's string representation.
     *
     * @param other The `Urn` instance to compare with this instance.
     * @return `true` if the provided `Urn` instance's string representation is equal to this URN's string representation,
     *         `false` otherwise.
     */
    fun equals(other: Urn): Boolean {
        return this.toUrnString() == other.toUrnString()
    }

    /**
     * Checks if this `Urn` instance is equal to a given string representation of a URN.
     *
     * The equality is determined by comparing the string representation of this URN,
     * generated by the `toUrnString` method, with the provided string.
     *
     * @param other The string representation of a URN to compare with this instance.
     * @return `true` if the provided string is equal to the string representation of this URN, `false` otherwise.
     */
    fun equals(other: String): Boolean {
        return this.toUrnString() == other
    }

    /**
     * Checks if this `Urn` instance is equal to another object.
     *
     * The equality of two `Urn` instances is determined by comparing their `namespace`, `nss`,
     * and `nid` properties.
     *
     * @param other The object to compare with this `Urn` instance.
     * @return `true` if the provided object is equal to this `Urn` instance, `false` otherwise.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Urn) return false

        if (namespace != other.namespace) return false
        if (nss != other.nss) return false
        if (nid != other.nid) return false

        return true
    }

    /**
     * Generates the hash code for the current `Urn` instance.
     * The hash code is calculated based on the `namespace`, `nss`, and `nid` properties
     * ensuring a consistent and unique value representative of the URN's state.
     *
     * @return The generated hash code as an integer.
     */
    override fun hashCode(): Int {
        var result = namespace.hashCode()
        result = 31 * result + nss.hashCode()
        result = 31 * result + (nid?.hashCode() ?: 0)
        return result
    }

    /**
     * Creates a copy of the current `Urn` instance.
     *
     * @return A new `Urn` instance with the same namespace, NSS, and NID values as the original.
     */
    fun copy(): Urn {
        return Urn(this)
    }

    companion object {
        private const val URN_PREFIX = "urn"
        private const val NID_URN = 4
        private const val MIN_URN_PARTS = 3
        private const val NID_START_INDEX = 2
        private const val NID_END_INDEX_OFFSET = 1

        /**
         * Parses a string representation of a URN (Uniform Resource Name) and returns an instance of the Urn class.
         *
         * @param urnString The string representation of the URN to be parsed.
         * @return An instance of the Urn class if the string can be successfully parsed, or null if the format is invalid.
         */


        fun parse(urnString: String): Urn? {
            val parts = urnString.split(":").filter { it.isNotBlank() }
            if (parts.size < MIN_URN_PARTS || parts[0] != URN_PREFIX) {
                return null
            }
            return if (parts.size >= NID_URN) {
                Urn(
                    namespace = parts[1],
                    nid = parts.subList(NID_START_INDEX, parts.size - NID_END_INDEX_OFFSET).toSet(),
                    nss = parts.last()
                )
            } else {
                Urn(namespace = parts[1], nss = parts[NID_START_INDEX])
            }
        }

    }
}


/**
 * Converts the current string to a URN (Uniform Resource Name) instance.
 *
 * @return An instance of the Urn class parsed from the current string.
 */
fun String.toUrn(): Urn? = Urn.parse(this)